[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino


lib_deps = 
    adafruit/Adafruit BusIO@^1.17.4
    adafruit/Adafruit PWM Servo Driver Library@^2.4.0

monitor_speed = 115200